service:
  - type: web
    name: quantum-safe-vault-frontend
    env: node
    buildCommand: npm run build
    startCommand: npx serve out
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          name: quantum-safe-vault-backend
          type: web
          envVarKey: URL

  - type: web
    name: quantum-safe-vault-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: CORS_ALLOW_ORIGINS
        fromService:
          name: quantum-safe-vault-frontend
          type: web
          envVarKey: URL